version: '3'
services:
  mongo:
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    restart: unless-stopped
    ports:
        - ${MONGO_PORT}:27017
    volumes:
        - mongo-data:/data/db

  client:
    container_name: ${COMPOSE_PROJECT_NAME}_mongoclient
    image: mongoclient/mongoclient
    environment:
        - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    restart: unless-stopped
    ports:
        - ${MONGO_CLIENT_PORT}:3000
    depends_on: 
        - mongo

volumes:
  mongo-data:
