version: '3.8'
services:
  mongo:
    container_name: ${COMPOSE_PROJECT_NAME}_mongo
    image: mongo:latest
    environment:
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    restart: unless-stopped
    networks:
        - antibes
    ports:
        - ${MONGO_PORT}:27017
    volumes:
        - mongo-data:/data/db
    labels:
      - "traefik.enable=false"

  client:
    container_name: ${COMPOSE_PROJECT_NAME}_mongoclient
    image: mongoclient/mongoclient
    environment:
        - MONGO_URL=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/
    restart: unless-stopped
    networks:
        - antibes
    depends_on: 
        - mongo
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.client.rule=Host(`mongo.dev-fullstack.net`)"
        - "traefik.http.routers.client.entrypoints=websecure"
        - "traefik.http.routers.client.tls.certresolver=myresolver"

volumes:
  mongo-data:

networks:
  antibes:
    external: true
    name: antibes
